package com.hfy.bottom.domain

enum class Sports(val id:Int,val type: String){
    Badminton(1,"羽毛球"),
    Tennis(2,"网球"),
    Basketball(3,"篮球"),
    Football(4,"足球"),
    Pingpang(5,"乒乓球"),
    Volleyball(6,"排球"),
    OneHundred(7,"100米"),
    TwoHundred(8,"200米"),
    FourHundred(9,"400米"),
    OneTAndHalfTousand(10,"1500米"),
    ThreeThousand(11,"3000米"),
    FiveThousand(12,"5000米"),
    TenThousand(13,"10000米"),
    StandingLongJump(14,"立定跳远"),
    Javelin(15,"标枪"),
    Discus(16,"铁饼"),
    ShotOut(17,"铅球"),
    Sockert(18,"橄榄球"),
    Baseball(19,"棒球"),
    Walking(20,"竞走"),
    Marathon(21,"马拉松"),
    Hurdles(22,"跨栏"),
    SteepleChase(23,"障碍赛"),
    PoleJump(24,"撑杆跳"),
    RelayRace(25,"接力赛"),
    Crawl(26,"蛙泳"),
    FreeStyle(27,"自由泳"),
    IndividualSpringboard(28,"3米跳板"),
    IndividualPlatform(29,"10米跳台")
}
